name: Publish Release

on:
  push:
    branches:
      - main
    # Only run if the commit is a version bump merge
    # (You can further restrict with a commit message filter if desired)

jobs:
  publish-release:
    if: contains(github.event.head_commit.message, 'chore: bump version to')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Automated release for ${{ steps.get_tag.outputs.tag }}.
          draft: false
          prerelease: false
