name: Publish Release

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
# test
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        run: |
          gh release create ${{ steps.get_tag.outputs.tag }} \
            --title "Release ${{ steps.get_tag.outputs.tag }}" \
            --generate-notes \
            ./sgp.h
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
