name: Build

on:
  push:
    tags:
      - 'v*'   # Only run on version tags

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git describe

      - name: Get version from git tag
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Update version in sgp.h and README.md
        run: |
          sed -i "s/Version: .*/Version: $VERSION/" sgp.h
          sed -i "s/SGP) v[0-9.]\+/SGP) $VERSION/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add inc/sgp/sgp.h inc/sgp/README.md
          git commit -m "chore: bump version to $VERSION [skip ci]" || echo "No changes to commit"
          git push